name: "Hello Actions"
decription: "Greet Someone"
author: "md-hexdrive"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"
    
runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
